---
inherit_from:
  - .rubocop_airbnb.yml

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['#', 'ENV']

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  SupportedStyles:
    - always

AllCops:
  TargetRubyVersion: 2.5

Airbnb/ClassOrModuleDeclaredInWrongFile:
  Enabled: false

Airbnb/ModuleMethodInWrongFile:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
